In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Ścieżki do folderów z danymi
train_dir = 'train set'
valid_dir = 'valid set'
test_dir = 'test set'


2023-07-07 13:46:14.915015: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# Przygotowanie danych treningowych
train_datagen = ImageDataGenerator(rescale=1./255)  # Przeskalowanie wartości pikseli do zakresu [0, 1]
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(150, 150),  # Rozmiar obrazów po przeskalowaniu
    batch_size=32,
    class_mode='categorical'  # Kategoryczne kodowanie etykiet
)


Found 9396 images belonging to 3 classes.


In [3]:
# Przygotowanie danych walidacyjnych
valid_datagen = ImageDataGenerator(rescale=1./255)
valid_generator = valid_datagen.flow_from_directory(
    valid_dir,
    target_size=(150, 150),
    batch_size=32,
    class_mode='categorical'
)

Found 290 images belonging to 3 classes.


In [4]:
# Przygotowanie danych testowych
test_datagen = ImageDataGenerator(rescale=1./255)
test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(150, 150),
    batch_size=32,
    class_mode='categorical'
)

# Przykładowe wyświetlenie etykiet (labels) dla danych treningowych
print(train_generator.class_indices)


Found 290 images belonging to 3 classes.
{'DUCK TRAIN': 0, 'EAGLE TRAIN': 1, 'SPARROW TRAIN': 2}


In [5]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

# Definicja modelu
model = Sequential()

# Dodanie warstw konwolucyjnych
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)))
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D((2, 2)))

model.add(Flatten())

# Dodanie warstw gęsto połączonych
model.add(Dense(512, activation='relu'))
model.add(Dense(3, activation='softmax'))  # 3 wyjścia dla trzech rzędów ptaków

# Kompilacja modelu
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

# Wyświetlenie podsumowania modelu
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 148, 148, 32)      896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 74, 74, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 72, 72, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 36, 36, 64)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 34, 34, 128)       73856     
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 17, 17, 128)      0

Trenowanie modelu: Do trenowania modelu, używam metody fit_generator i przekazuję dane treningowe za pomocą generatora train_generator. Możemy ustawić liczbę epok trenowania, rozmiar partii (batch_size), a także przekazać generator danych walidacyjnych (valid_generator) do monitorowania postępów podczas trenowania.

In [6]:
history = model.fit_generator(
    train_generator,
    steps_per_epoch=100,  # Liczba kroków na jedną epokę 
    epochs=10,  # Liczba epok trenowania 
    validation_data=valid_generator,
    validation_steps=50  # Liczba kroków walidacji 
)


/var/folders/rr/3tz5xt4j16s1wvxsg7zr8hg80000gn/T/ipykernel_28205/3683063078.py:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history = model.fit_generator(
2023-07-07 13:51:27.944578: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]


Epoch 1/10
100/100 [==============================] - ETA: 0s - loss: 1.0092 - accuracy: 0.4709

2023-07-07 13:52:15.432504: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]


100/100 [==============================] - 50s 482ms/step - loss: 1.0092 - accuracy: 0.4709 - val_loss: 0.8189 - val_accuracy: 0.6103
Epoch 2/10
100/100 [==============================] - 47s 469ms/step - loss: 0.8429 - accuracy: 0.6206
Epoch 3/10
100/100 [==============================] - 46s 455ms/step - loss: 0.7051 - accuracy: 0.6976
Epoch 4/10
100/100 [==============================] - 45s 449ms/step - loss: 0.6245 - accuracy: 0.7416
Epoch 5/10
100/100 [==============================] - 45s 452ms/step - loss: 0.5441 - accuracy: 0.7812
Epoch 6/10
100/100 [==============================] - 51s 505ms/step - loss: 0.5041 - accuracy: 0.8008
Epoch 7/10
100/100 [==============================] - 46s 462ms/step - loss: 0.4397 - accuracy: 0.8175
Epoch 8/10
100/100 [==============================] - 47s 469ms/step - loss: 0.3859 - accuracy: 0.8500
Epoch 9/10
100/100 [==============================] - 46s 454ms/step - loss: 0.3470 - accuracy: 0.8641
Epoch 10/10
100/100 [=====================

**Ewaluacja modelu:** 
Po zakończeniu trenowania możemy ocenić wydajność modelu na danych walidacyjnych. Możemy użyć metody evaluate_generator i przekazać generator danych walidacyjnych (valid_generator).

In [7]:
loss, accuracy = model.evaluate_generator(valid_generator)
print("Loss: {:.2f}".format(loss))
print("Accuracy: {:.2f}%".format(accuracy * 100))


/var/folders/rr/3tz5xt4j16s1wvxsg7zr8hg80000gn/T/ipykernel_28205/588715195.py:1: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  loss, accuracy = model.evaluate_generator(valid_generator)
2023-07-07 14:01:02.574754: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]


Loss: 0.45
Accuracy: 84.83%


**Testowanie modelu:** 
Możemy również przetestować nasz wytrenowany model na danych testowych, które były wcześniej odłożone. Użyjemy metody evaluate_generator i przekazujemy generator danych testowych (test_generator)

In [8]:
loss, accuracy = model.evaluate_generator(test_generator)
print("Loss: {:.2f}".format(loss))
print("Accuracy: {:.2f}%".format(accuracy * 100))


/var/folders/rr/3tz5xt4j16s1wvxsg7zr8hg80000gn/T/ipykernel_28205/3691433002.py:1: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  loss, accuracy = model.evaluate_generator(test_generator)
2023-07-07 14:01:19.874411: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]


Loss: 0.40
Accuracy: 85.52%


In [10]:
import numpy as np

# Pobranie predykcji i prawdziwych etykiet z generatora danych testowych
predictions = model.predict_generator(test_generator)
predicted_labels = np.argmax(predictions, axis=1)
true_labels = test_generator.classes

# Obliczenie dokładności (accuracy)
accuracy = np.mean(predicted_labels == true_labels)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Obliczenie macierzy pomyłek
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(true_labels, predicted_labels)
print("Confusion Matrix:")
print(cm)

# Obliczenie precyzji, czułości i miary F1
from sklearn.metrics import classification_report
target_names = list(test_generator.class_indices.keys())
print("Classification Report:")
print(classification_report(true_labels, predicted_labels, target_names=target_names))


/var/folders/rr/3tz5xt4j16s1wvxsg7zr8hg80000gn/T/ipykernel_28205/1529198355.py:4: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  predictions = model.predict_generator(test_generator)
2023-07-07 14:06:23.015004: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]


Accuracy: 33.45%
Confusion Matrix:
[[27 23 45]
 [25 33 37]
 [24 39 37]]
Classification Report:
              precision    recall  f1-score   support

        DUCK       0.36      0.28      0.32        95
       EAGLE       0.35      0.35      0.35        95
     SPARROW       0.31      0.37      0.34       100

    accuracy                           0.33       290
   macro avg       0.34      0.33      0.33       290
weighted avg       0.34      0.33      0.33       290



**Predykcja na nowych danych:** 
Przewidywanie gatunków ptaków na nowych, nieznanych wcześniej danych, używam metody predict_generator i przekazuję generator danych testowych (test_generator). Predykcje będą w formie prawdopodobieństw dla każdej klasy.

In [9]:
predictions = model.predict_generator(test_generator)


/var/folders/rr/3tz5xt4j16s1wvxsg7zr8hg80000gn/T/ipykernel_28205/1414481863.py:1: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  predictions = model.predict_generator(test_generator)
2023-07-07 14:01:53.634826: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'Placeholder/_0' with dtype int32
	 [[{{node Placeholder/_0}}]]
